/**
 * PROJECTS / CASE STUDIES
 * ------------------------------------------------------------------
 * Source: application and website list from the previous site
 * (src/data/companies.js, src/pages/Websites.jsx).
 *
 * Login links are NOT typed here. `apps` points at the application in
 * src/data/companies.js — [companyId, appId] — and the login URL is read
 * from there, so a link only ever needs changing in ONE place.
 * Use ['common', 'audit'] for the group-wide Audit system.
 * Public websites carry a `liveUrl`. User counts and employee data are not shown.
 *
 * To add a project, copy one object below. `image` is a key from
 * src/content/images.js (or null to show the generated module diagram).
 *
 * TODO(management): confirm each project is approved for public showcase
 * (set `showcase: false` to hide) and verify the `tech` lists.
 */

export const PROJECT_CATEGORIES = ['All', 'Business application', 'Website']

export const PROJECTS = [
  {
    slug: 'design-management-system',
    name: 'Design Management System',
    code: 'VDMS',
    category: 'Business application',
    industry: 'Electrical engineering services',
    type: 'Custom web application',
    status: 'Live',
    featured: true,
    summary: 'End-to-end design workflow from enquiry to client delivery, with project and time tracking in one place.',
    problem: 'Design enquiries, project progress, engineer time and collections were tracked separately, making it hard to see project status or bill accurately.',
    solution: 'A single workflow application covering enquiry, project, time, collection and client management, with automated client mail so customers are kept informed without manual follow-up.',
    features: ['Enquiry management', 'Project management', 'Time management', 'Collection management', 'Client management', 'Client mail automation'],
    tech: ['Laravel', 'PHP', 'MySQL', 'JavaScript'],
    outcome: 'Engineering, project and accounts teams work from the same record for every project.',
    apps: [['vepl', 'vdms']],
    liveUrl: null,
    image: null,
    showcase: true,
  },
  {
    slug: 'hr-management-system',
    name: 'HR Management System',
    code: 'HRMS',
    category: 'Business application',
    industry: 'Multi-company group',
    type: 'Enterprise web application',
    status: 'Live',
    featured: true,
    summary: 'Complete HR lifecycle from recruitment to payroll, statutory compliance and insurance, deployed across several group companies.',
    problem: 'Each company handled recruitment, leave, payroll and statutory filings differently, with heavy manual effort every month.',
    solution: 'A shared HR platform configured per company, covering recruitment, leave, payroll with payslip mailing, bonus, statutory compliance, insurance and MIS reports.',
    features: ['Recruitment', 'Post-recruitment onboarding', 'Payroll & payslip mail', 'Leave management', 'Bonus', 'Statutory compliance', 'Insurance', 'MIS reports'],
    tech: ['React', 'Node.js', 'Express.js', 'MySQL'],
    outcome: 'One HR process across companies, with each company’s data kept separate.',
    apps: [['vepl', 'vepl-hrms'], ['vmcl', 'vmcl-hrms'], ['vipra', 'vipra-hrms'], ['bliss', 'bliss-hrms']],
    liveUrl: null,
    image: null,
    showcase: true,
  },
  {
    slug: 'supply-chain-management',
    name: 'Supply Chain Management',
    code: 'Prime',
    category: 'Business application',
    industry: 'Manufacturing',
    type: 'ERP module suite',
    status: 'Live',
    featured: true,
    summary: 'Enquiry-to-invoice supply chain for a manufacturing business — CRM, orders, BOM, purchase, goods receipt, QC and dispatch.',
    problem: 'Orders moved between sales, planning, purchase and stores on paper and spreadsheets, causing delays and stock mismatches.',
    solution: 'A connected flow from CRM enquiry to sales order, work order, purchase requisition, reservation, BOM, purchase order, GRN, outward QC and invoice dispatch.',
    features: ['CRM – enquiry to order', 'Sales order', 'Work order', 'Purchase requisition', 'Reservation', 'Bill of materials', 'Purchase order', 'GRN', 'Outward QC', 'Invoice dispatch'],
    tech: ['Laravel', 'PHP', 'MySQL', 'JavaScript'],
    outcome: 'Every order can be traced from the first enquiry to the dispatched invoice.',
    apps: [['vmcl', 'prime']],
    liveUrl: null,
    image: null,
    showcase: true,
  },
  {
    slug: 'project-cost-management',
    name: 'Project Cost Management',
    code: 'VPMT',
    category: 'Business application',
    industry: 'Engineering projects',
    type: 'Web application',
    status: 'Live',
    featured: true,
    summary: 'Project cost visibility comparing site and head-office spend, with budget variance tracking.',
    problem: 'Management could only see project profitability after closure, when it was too late to act on overruns.',
    solution: 'Live cost tracking per project, split between site and head-office costs, with variance analysis against budget and cost reports.',
    features: ['Project cost tracking', 'Site vs head-office cost', 'Budget variance analysis', 'Cost management reports'],
    tech: ['React', 'TypeScript', 'Tailwind CSS', 'Laravel', 'MySQL'],
    outcome: 'Cost overruns are visible while a project is still running.',
    apps: [['vepl', 'vpmt']],
    liveUrl: null,
    image: null,
    showcase: true,
  },
  {
    slug: 'finance-management',
    name: 'Finance Management System',
    code: 'VEFM',
    category: 'Business application',
    industry: 'Engineering services',
    type: 'Web application',
    status: 'Live',
    summary: 'Timesheets, budgets, invoices, engineer expenses and travel expense statements for an engineering services business.',
    problem: 'Timesheets, expense claims and invoicing were handled in separate files, delaying billing and reimbursements.',
    solution: 'One finance application linking timesheets and budgets to invoices, collections and engineer travel expense statements.',
    features: ['Timesheet', 'Budget management', 'Invoice processing', 'Engineer expenses', 'Collection', 'Travel expense statements'],
    tech: ['Laravel', 'PHP', 'MySQL'],
    outcome: 'Billing and expense processing run from the same source data.',
    apps: [['vepl', 'vefm']],
    liveUrl: null,
    image: null,
    showcase: true,
  },
  {
    slug: 'international-expense-flow',
    name: 'International Expense Flow',
    code: 'ExpenseFlow',
    category: 'Business application',
    industry: 'International operations',
    type: 'Web application',
    status: 'Live',
    summary: 'International expense and cash-flow management covering targets, margins, vendor bills, customer invoices and collections.',
    problem: 'Overseas operations needed a clear view of margins, advances and receivables across vendors and customers.',
    solution: 'A focused application for target and operation-margin tracking, advance entries, vendor bills and payments, customer invoices and collection.',
    features: ['Target management', 'Operation margin', 'Advance entry', 'Vendor bills & payments', 'Customer invoice', 'Collection'],
    tech: ['Laravel', 'PHP', 'MySQL'],
    outcome: 'Margins and cash position are tracked per operation rather than reconstructed at month end.',
    apps: [['vepl', 'expenseflow']],
    liveUrl: null,
    image: null,
    showcase: true,
  },
  {
    slug: 'instrumentation-management',
    name: 'Instrumentation Project Management',
    code: 'VVEP',
    category: 'Business application',
    industry: 'Instrumentation & automation',
    type: 'Web application',
    status: 'Live',
    summary: 'Integrated enquiry-to-billing system for an instrumentation and automation projects business.',
    problem: 'Marketing visits, offers, orders and project timesheets were not connected to billing.',
    solution: 'One flow from marketing visit and enquiry through offer, order, purchase order and project timesheet to invoice billing.',
    features: ['Marketing visits', 'Enquiry management', 'Offer management', 'Order management', 'Purchase order', 'Project timesheet', 'Invoice billing'],
    tech: ['Laravel', 'PHP', 'MySQL'],
    outcome: 'Sales and project teams share one record from first visit to final invoice.',
    apps: [['vipra', 'vvep']],
    liveUrl: null,
    image: null,
    showcase: true,
  },
  {
    slug: 'employee-management-system',
    name: 'Employee Management System',
    code: 'EMS',
    category: 'Business application',
    industry: 'HR & staffing services',
    type: 'High-volume web application',
    status: 'Live',
    summary: 'High-volume employee management with payroll, attendance, MIS reports and an HR support portal for a staffing business.',
    problem: 'Managing payroll and attendance for a large deployed workforce required significant manual reconciliation.',
    solution: 'Centralised employee records with attendance, payroll processing, MIS reporting and a support portal for HR queries.',
    features: ['MIS reports', 'Payroll processing', 'Attendance management', 'HR support portal'],
    tech: ['Laravel', 'PHP', 'MySQL'],
    outcome: 'Payroll and attendance handled in one system at scale.',
    apps: [['vhrs', 'ems']],
    liveUrl: null,
    image: null,
    showcase: true,
  },
  {
    slug: 'crm-ats',
    name: 'CRM & Applicant Tracking',
    code: 'CRM · IMS',
    category: 'Business application',
    industry: 'HR & staffing services',
    type: 'Web application',
    status: 'Live',
    summary: 'Client engagement, pipeline conversion and drag-and-drop candidate tracking with background verification.',
    problem: 'Client requirements and candidate progress were tracked separately, slowing down hiring and client reporting.',
    solution: 'CRM for client engagements and pipeline tracking, combined with an applicant tracking system, hiring-velocity dashboard and background verification.',
    features: ['Client engagements', 'Pipeline conversion tracking', 'Applicant tracking (drag & drop)', 'Hiring velocity dashboard', 'Background verification'],
    tech: ['Laravel', 'PHP', 'MySQL', 'JavaScript'],
    outcome: 'Recruiters and account managers see the same pipeline in real time.',
    apps: [['vhrs', 'crm'], ['vhrs', 'ims']],
    liveUrl: null,
    image: null,
    showcase: true,
  },
  {
    slug: 'audit-compliance',
    name: 'Audit & Compliance Management',
    code: 'AUDIT',
    category: 'Business application',
    industry: 'Multi-company group',
    type: 'Web application',
    status: 'Live',
    summary: 'Group-wide audit, ISO certificate, document and compliance management.',
    problem: 'Audit preparation, ISO certificates and non-conformances were tracked manually across several companies.',
    solution: 'A shared system for ISO certificate and document management, audit scheduling, safety management and non-conformance tracking.',
    features: ['ISO certificate management', 'Document management', 'Compliance management', 'Audit scheduling', 'Safety management', 'Non-conformance tracking'],
    tech: ['Laravel', 'PHP', 'MySQL'],
    outcome: 'Compliance status is maintained continuously instead of before each audit.',
    apps: [['common', 'audit']],
    liveUrl: null,
    image: null,
    showcase: true,
  },
  {
    slug: 'asset-management',
    name: 'Asset Management System',
    code: 'VAMS',
    category: 'Business application',
    industry: 'Facility management',
    type: 'Web application',
    status: 'Live',
    summary: 'IT and non-IT asset lifecycle management with ticketing, mail requests and purchase flow.',
    problem: 'Asset records and service requests were handled over email with no central register.',
    solution: 'Asset registers for IT and non-IT items, ticket raising, mail-based requests and purchase orders in one application.',
    features: ['IT asset management', 'Non-IT asset management', 'Ticket raise', 'Mail request system', 'Purchase order'],
    tech: ['Laravel', 'PHP', 'MySQL'],
    outcome: 'Every asset and request has an owner and a history.',
    apps: [['bliss', 'vams']],
    liveUrl: null,
    image: null,
    showcase: true,
  },
  {
    slug: 'vendor-process',
    name: 'Vendor Process Management',
    code: 'VEVP',
    category: 'Business application',
    industry: 'Engineering procurement',
    type: 'Web application',
    status: 'Live',
    summary: 'Vendor onboarding and process tracking for engineering procurement.',
    problem: 'Vendor registration and approvals relied on emails and documents passed between teams.',
    solution: 'Structured vendor onboarding with process tracking tied to engineering procurement workflows.',
    features: ['Vendor onboarding', 'Vendor process tracking', 'Engineering procurement'],
    tech: ['Laravel', 'PHP', 'MySQL'],
    outcome: 'Vendor status is visible to procurement and engineering at every stage.',
    apps: [['vepl', 'vevp']],
    liveUrl: null,
    image: null,
    showcase: true,
  },
  {
    slug: 'health-safety',
    name: 'Employee Health & Safety',
    code: 'EHS',
    category: 'Business application',
    industry: 'Engineering services',
    type: 'Web application',
    status: 'Live',
    summary: 'Workplace safety management with incident tracking and compliance monitoring.',
    problem: 'Safety incidents and compliance checks were recorded inconsistently.',
    solution: 'A dedicated application for safety management, incident tracking and compliance monitoring.',
    features: ['Employee safety management', 'Safety incident tracking', 'Compliance monitoring'],
    tech: ['Laravel', 'PHP', 'MySQL'],
    outcome: 'Incidents and safety checks are recorded the same way every time.',
    apps: [['vepl', 'ehs']],
    liveUrl: null,
    image: null,
    showcase: true,
  },
  {
    slug: 'job-field-workforce-management',
    name: 'Job & Field Workforce Management',
    code: 'VBMS',
    category: 'Business application',
    industry: 'Electrical engineering services',
    type: 'Mobile application',
    status: 'Live',
    summary: 'Mobile-first job management with GPS-verified attendance and end-to-end tracking of every job, from creation to completion.',
    // TODO(management): review problem / solution / outcome wording and add the tech stack
    problem: 'Field staff attendance and job progress were tracked by phone calls and spreadsheets, making it hard to confirm who was on site and where each job stood.',
    solution: 'A mobile application where staff mark attendance with GPS location, and every job is managed through its full lifecycle — from creation and assignment to completion.',
    features: ['Attendance & GPS', 'End-to-end job lifecycle', 'Job management'],
    tech: [],
    outcome: 'Attendance and job status are visible from one place, in real time.',
    apps: [['vepl', 'vbms']],
    liveUrl: null,
    image: null,
    showcase: true,
  },
  {
    slug: 'production-erp',
    name: 'Production ERP',
    code: 'ERP',
    category: 'Business application',
    industry: 'Manufacturing',
    type: 'ERP maintenance & modernisation',
    status: 'Live',
    summary: 'Long-running production ERP covering sales, purchase, production planning, inventory and accounts — maintained and extended by the team.',
    problem: 'A business-critical legacy ERP needed continuous support while newer modules were introduced alongside it.',
    solution: 'Ongoing maintenance and enhancement of the existing system, with new supply-chain modules built to work alongside it.',
    features: ['Sales management', 'Purchase management', 'Production planning', 'Inventory', 'Accounts & finance'],
    tech: ['PHP', 'MySQL'],
    outcome: 'Daily production operations continue uninterrupted during modernisation.',
    apps: [['vmcl', 'vmcl-erp']],
    liveUrl: null,
    image: null,
    showcase: true,
  },

  // ─── WEBSITES (public, safe to link) ─────────────────────────────
  {
    slug: 'voltech-group-website',
    name: 'Voltech Group corporate website',
    code: 'Website',
    category: 'Website',
    industry: 'Electrical engineering',
    type: 'Corporate website',
    status: 'Live',
    featured: true,
    summary: 'Main corporate website showcasing engineering products, presence, careers and community initiatives.',
    problem: 'The group needed a single, credible digital identity for its engineering business.',
    solution: 'A responsive corporate website with structured product and company sections, on-page SEO and analytics.',
    features: ['Responsive design', 'On-page SEO', 'Google Analytics 4', 'Careers section'],
    tech: ['Responsive web', 'SEO', 'Google Analytics'],
    outcome: 'A clear first point of contact for customers and candidates.',
    liveUrl: 'https://voltechgroup.com/',
    image: 'siteVg',
    showcase: true,
  },
  {
    slug: 'manufacturing-products-website',
    name: 'Manufacturing products website',
    code: 'Website',
    category: 'Website',
    industry: 'Manufacturing',
    type: 'Product website',
    status: 'Live',
    summary: 'Product website for transformers, switchgear and control panels, with a catalogue and quote request.',
    problem: 'Buyers needed technical product information and an easy way to request a quote.',
    solution: 'A product catalogue website with technical specifications and a quote request system.',
    features: ['Product catalogue', 'Technical specifications', 'Quote request', 'On-page SEO'],
    tech: ['Responsive web', 'SEO', 'Google Analytics'],
    outcome: 'Product enquiries arrive with the right details attached.',
    liveUrl: 'https://products.voltechgroup.com/',
    image: 'siteVmcl',
    showcase: true,
  },
  {
    slug: 'instrumentation-website',
    name: 'Instrumentation & automation website',
    code: 'Website',
    category: 'Website',
    industry: 'Instrumentation & automation',
    type: 'Corporate website',
    status: 'Live',
    summary: 'Engineering website covering instrumentation, fire solutions, automation panel design and project execution.',
    problem: 'The business needed to present specialised engineering capabilities to industrial clients.',
    solution: 'A service-led website organised around capabilities and project execution.',
    features: ['Service pages', 'Responsive design', 'On-page SEO', 'Enquiry form'],
    tech: ['Responsive web', 'SEO', 'Google Analytics'],
    outcome: 'Capabilities are explained clearly to industrial buyers.',
    liveUrl: 'https://voltechvipra.com/',
    image: 'siteVipra',
    showcase: true,
  },
  {
    slug: 'facility-management-website',
    name: 'Facility management services website',
    code: 'Website',
    category: 'Website',
    industry: 'Facility management',
    type: 'Service website',
    status: 'Live',
    summary: 'Website for facility management, security, housekeeping and technical services.',
    problem: 'Corporate and industrial clients needed a clear overview of the service range.',
    solution: 'A service website with clear service categories and enquiry paths.',
    features: ['Service catalogue', 'Responsive design', 'On-page SEO', 'Enquiry form'],
    tech: ['Responsive web', 'SEO', 'Google Analytics'],
    outcome: 'Service offerings are presented in one clear place.',
    liveUrl: 'https://voltechvipra.com/bliss/',
    image: 'siteBliss',
    showcase: true,
  },

  // ─── IN DEVELOPMENT ──────────────────────────────────────────────
  {
    slug: 'operations-management-system',
    name: 'Operations Management System',
    code: 'OMS',
    category: 'Business application',
    industry: 'Operation & maintenance',
    type: 'Web & mobile application',
    status: 'In development',
    summary: 'Work orders, preventive maintenance, asset health and field engineer dispatch for an O&M services business.',
    problem: 'Operation and maintenance workflows are being moved from manual tracking into a dedicated system.',
    solution: 'A planned system covering work orders, preventive maintenance scheduling, asset health, field dispatch, SLA reporting and downtime analytics.',
    features: ['Work order management', 'Preventive maintenance scheduling', 'Asset health tracking', 'Field engineer dispatch', 'SLA & compliance reporting', 'Downtime analytics'],
    tech: [], // TODO: add once the stack is final
    outcome: 'In development.',
    liveUrl: null,
    image: null,
    showcase: true,
  },
]

export const visibleProjects = () => PROJECTS.filter((p) => p.showcase)
export const featuredProjects = () => PROJECTS.filter((p) => p.showcase && p.featured)
export const getProject = (slug) => PROJECTS.find((p) => p.slug === slug && p.showcase)
